version: '3.8'

services:
  # Frontend - Next.js Application
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000"]
